services:
  serverest:
    image: paulogoncalvesbh/serverest:latest
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/status || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
